-- Adicionando colunas de estatísticas de combate e missões à tabela players
ALTER TABLE public.players
ADD COLUMN IF NOT EXISTS wins_dojo INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS losses_dojo INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS wins_pvp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS losses_pvp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fugas INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS missions_s INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS missions_a INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS missions_b INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS missions_c INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS missions_d INTEGER DEFAULT 0;
